# Generated by Django 5.2.5 on 2025-09-05 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='social_id',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='social_provider',
        ),
    ]
