# Generated by Django 5.2.5 on 2025-09-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_userdetail_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
