# Generated by Django 5.2.5 on 2025-09-17 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userdetail_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='profile_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
