# Generated by Django 5.2.5 on 2025-11-12 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'InsuranceCompany',
            },
        ),
        migrations.CreateModel(
            name='InsurancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='insurance.insurancecompany')),
            ],
            options={
                'verbose_name_plural': 'InsurancePlan',
            },
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('insurance_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insurance_date', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField()),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurance_set', to='vehicles.vehicle')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurances', to='insurance.insuranceplan')),
            ],
            options={
                'verbose_name_plural': 'Insurance',
            },
        ),
        migrations.CreateModel(
            name='VehicleTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('Private Vehicle (5 seater-EV)', 'Car (EV)'), ('Private Vehicle (5 seater)', 'Car'), ('Motorcycles (EV)', 'Motorcycle (EV)'), ('Motorcycles', 'Motorcycle')], max_length=50)),
                ('min_engine_cc', models.IntegerField(blank=True, help_text='Minimum CC (non-EVs)', null=True)),
                ('max_engine_cc', models.IntegerField(blank=True, help_text='Maximum CC (non-EVs)', null=True)),
                ('min_engine_wattage', models.IntegerField(blank=True, help_text='Minimum Wattage (EVs)', null=True)),
                ('max_engine_wattage', models.IntegerField(blank=True, help_text='Maximum Wattage (EVs)', null=True)),
            ],
            options={
                'verbose_name': 'Vehicle Tier',
                'verbose_name_plural': 'Vehicle Tiers',
                'unique_together': {('vehicle_type', 'min_engine_cc', 'max_engine_cc', 'min_engine_wattage', 'max_engine_wattage')},
            },
        ),
        migrations.AddField(
            model_name='insuranceplan',
            name='vehicle_tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='insurance.vehicletier'),
        ),
        migrations.AlterUniqueTogether(
            name='insuranceplan',
            unique_together={('company', 'vehicle_tier')},
        ),
    ]
