# Generated by Django 5.2.5 on 2025-09-02 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reminder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('insurance_id', models.AutoField(primary_key=True, serialize=False)),
                ('insurance_company', models.CharField(max_length=50)),
                ('payment_mode', models.CharField(max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insurance_date', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField()),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reminder.reminder')),
            ],
            options={
                'verbose_name_plural': 'Insurance',
            },
        ),
    ]
