# Generated by Django 5.2.5 on 2025-09-12 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
        ('vehicles', '0002_vehicle_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurance',
            name='reminder',
        ),
        migrations.AddField(
            model_name='insurance',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle'),
        ),
    ]
