# Generated by Django 5.2.5 on 2025-11-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_seed_initial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicletier',
            name='vehicle_type',
            field=models.CharField(choices=[('Car (EV)', 'Car (EV)'), ('Car', 'Car'), ('Motorcycle (EV)', 'Motorcycle (EV)'), ('Motorcycle', 'Motorcycle')], max_length=50),
        ),
    ]
