# Generated by Django 5.2.5 on 2025-10-01 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_remove_insurance_reminder_insurance_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='insurance_company',
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='payment_mode',
        ),
        migrations.CreateModel(
            name='InsurancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('bike', 'Bike'), ('truck', 'Truck'), ('bus', 'Bus')], max_length=20)),
                ('payment_mode', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='insurance.insurancecompany')),
            ],
            options={
                'unique_together': {('company', 'vehicle_type', 'payment_mode')},
            },
        ),
        migrations.AddField(
            model_name='insurance',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurances', to='insurance.insuranceplan'),
        ),
    ]
