# Generated by Django 5.2.5 on 2025-10-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0003_insurancecompany_remove_insurance_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insurancecompany',
            options={'verbose_name_plural': 'InsuranceCompany'},
        ),
        migrations.AlterModelOptions(
            name='insuranceplan',
            options={'verbose_name_plural': 'InsurancePlan'},
        ),
        migrations.AlterField(
            model_name='insuranceplan',
            name='vehicle_type',
            field=models.CharField(choices=[('car', 'Car'), ('bike', 'Bike'), ('truck', 'Truck'), ('bus', 'Bus')], default='bike', max_length=20),
        ),
    ]
