# Generated by Django 5.2.5 on 2025-10-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0004_alter_insurancecompany_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceplan',
            name='vehicle_type',
            field=models.CharField(choices=[('Car', 'Car'), ('Motorcycle', 'Bike'), ('Truck', 'Truck'), ('Bus', 'Bus')], default='Motorcycle', max_length=20),
        ),
    ]
