# Generated by Django 5.2.5 on 2025-11-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0007_auto_20251011_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceplan',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='insuranceplan',
            name='vehicle_type',
            field=models.CharField(choices=[('Private Vehicle (5 seater-EV)', 'Car (EV)'), ('Private Vehicle (5 seater)', 'Car'), ('Motorcycles (EV)', 'Motorcycle (EV)'), ('Motorcycles', 'Motorcycle')], default='Motorcycle', max_length=40),
        ),
    ]
