# Generated by Django 5.2.5 on 2025-11-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0008_alter_insuranceplan_payment_mode_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='insuranceplan',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='insuranceplan',
            name='max_engine_cc',
            field=models.IntegerField(blank=True, help_text='Maximum CC for this plan (non-EVs)', null=True),
        ),
        migrations.AddField(
            model_name='insuranceplan',
            name='max_engine_wattage',
            field=models.IntegerField(blank=True, help_text='Maximum Wattage for this plan (EVs)', null=True),
        ),
        migrations.AddField(
            model_name='insuranceplan',
            name='min_engine_cc',
            field=models.IntegerField(blank=True, help_text='Minimum CC for this plan (non-EVs)', null=True),
        ),
        migrations.AddField(
            model_name='insuranceplan',
            name='min_engine_wattage',
            field=models.IntegerField(blank=True, help_text='Minimum Wattage for this plan (EVs)', null=True),
        ),
    ]
