# Generated by Django 5.2.5 on 2025-11-10 17:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models





def create_default_vehicletier(apps, schema_editor):
    VehicleTier = apps.get_model('insurance', 'VehicleTier')
    # Make sure the id matches what you're going to use as default
    VehicleTier.objects.create(
        id=1,
        vehicle_type='Private Vehicle (5 seater-EV)',
        min_engine_cc=None,
        max_engine_cc=None,
        min_engine_wattage=0,
        max_engine_wattage=19999
    )



class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0009_alter_insuranceplan_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('Private Vehicle (5 seater-EV)', 'Car (EV)'), ('Private Vehicle (5 seater)', 'Car'), ('Motorcycles (EV)', 'Motorcycle (EV)'), ('Motorcycles', 'Motorcycle')], max_length=50)),
                ('min_engine_cc', models.IntegerField(blank=True, help_text='Minimum CC (non-EVs)', null=True)),
                ('max_engine_cc', models.IntegerField(blank=True, help_text='Maximum CC (non-EVs)', null=True)),
                ('min_engine_wattage', models.IntegerField(blank=True, help_text='Minimum Wattage (EVs)', null=True)),
                ('max_engine_wattage', models.IntegerField(blank=True, help_text='Maximum Wattage (EVs)', null=True)),
            ],
            options={
                'verbose_name': 'Vehicle Tier',
                'verbose_name_plural': 'Vehicle Tiers',
                'unique_together': {('vehicle_type', 'min_engine_cc', 'max_engine_cc', 'min_engine_wattage', 'max_engine_wattage')},
            },
        ),
        migrations.RunPython(create_default_vehicletier),
        migrations.AddField(
            model_name='insuranceplan',
            name='vehicle_tier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='insurance.vehicletier'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='insuranceplan',
            unique_together={('company', 'vehicle_tier')},
        ),
        migrations.RemoveField(
            model_name='insuranceplan',
            name='max_engine_cc',
        ),
        migrations.RemoveField(
            model_name='insuranceplan',
            name='max_engine_wattage',
        ),
        migrations.RemoveField(
            model_name='insuranceplan',
            name='min_engine_cc',
        ),
        migrations.RemoveField(
            model_name='insuranceplan',
            name='min_engine_wattage',
        ),
        migrations.RemoveField(
            model_name='insuranceplan',
            name='payment_mode',
        ),
        migrations.RemoveField(
            model_name='insuranceplan',
            name='vehicle_type',
        ),
    ]
