# Generated by Django 5.2.5 on 2025-11-11 06:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0012_populate_initial_plans_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=10.00, max_digits=10),
            preserve_default=False,
        ),
    ]
