# Generated by Django 5.2.5 on 2025-11-11 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0013_insurance_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurance',
            name='amount',
        ),
    ]
