# Generated by Django 5.2.5 on 2025-11-11 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0014_remove_insurance_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
            preserve_default=False,
        ),
    ]
