# Generated by Django 5.2.5 on 2025-11-12 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0015_insurance_amount'),
        ('vehicles', '0006_bluebookrenewal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurance_set', to='vehicles.vehicle'),
        ),
    ]
