# Generated by Django 5.2.5 on 2025-09-02 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('families', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('family_member_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=100)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='families.family')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userdetail')),
            ],
            options={
                'verbose_name_plural': 'FamilyMember',
            },
        ),
    ]
