# Generated by Django 5.2.5 on 2025-09-05 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familymember', '0001_initial'),
        ('users', '0002_remove_userdetail_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userdetail', unique=True),
        ),
    ]
