# Generated by Django 5.2.5 on 2025-11-12 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('familymember', '0001_initial'),
        ('users', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpoPushToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.userdetail')),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('reminder_id', models.AutoField(primary_key=True, serialize=False)),
                ('target_type', models.CharField(default='insurance', max_length=30)),
                ('last_sent', models.DateTimeField(blank=True, null=True)),
                ('snoozed_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('frequency', models.CharField(choices=[('1d', 'Daily'), ('3d', '3 Days'), ('7d', 'Weekly'), ('14d', '14 Days'), ('30d', 'Monthly')], default='7d', max_length=30)),
                ('family_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familymember.familymember')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle')),
            ],
            options={
                'verbose_name_plural': 'Reminder',
            },
        ),
    ]
