# Generated by Django 5.2.5 on 2025-09-02 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('familymember', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('reminder_id', models.AutoField(primary_key=True, serialize=False)),
                ('target_type', models.CharField(max_length=30)),
                ('reminder_date', models.DateTimeField(auto_now_add=True)),
                ('snoozed_until', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('family_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familymember.familymember')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle')),
            ],
            options={
                'verbose_name_plural': 'Reminder',
            },
        ),
    ]
