# Generated by Django 5.2.5 on 2025-11-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='frequency_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='frequency',
            field=models.CharField(choices=[('1d', '1 day before expiry'), ('7d', '1 week before expiry'), ('14d', '2 weeks before expiry'), ('30d', '30 days before expiry')], default='1d', max_length=30),
        ),
    ]
