# Generated by Django 5.2.5 on 2025-11-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0002_reminder_frequency_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='frequency',
            field=models.CharField(choices=[('1d', '1 day before expiry'), ('3d', '3 days before expiry'), ('7d', '1 week before expiry'), ('14d', '2 weeks before expiry'), ('30d', '30 days before expiry')], default='1d', max_length=30),
        ),
    ]
