# Generated by Django 5.2.5 on 2025-09-13 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_remove_insurance_reminder_insurance_vehicle'),
        ('reminder', '0002_reminder_frequency_reminder_is_expired_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='is_expired',
        ),
        migrations.AddField(
            model_name='reminder',
            name='insurance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance.insurance'),
        ),
    ]
