# Generated by Django 5.2.5 on 2025-09-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0003_remove_reminder_is_expired_reminder_insurance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='snoozed_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
