# Generated by Django 5.2.5 on 2025-10-14 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0004_alter_reminder_snoozed_until'),
        ('users', '0004_userdetail_profile_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='reminder_date',
        ),
        migrations.AddField(
            model_name='reminder',
            name='last_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='frequency',
            field=models.CharField(choices=[('1d', 'Daily'), ('3d', '3 Days'), ('7d', 'Weekly'), ('14d', '14 Days'), ('30d', 'Monthly')], default='weekly', max_length=30),
        ),
        migrations.CreateModel(
            name='ExpoPushToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.userdetail')),
            ],
        ),
    ]
