# Generated by Django 5.2.5 on 2025-10-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0005_remove_reminder_reminder_date_reminder_last_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expopushtoken',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
    ]
