# Generated by Django 5.2.5 on 2025-10-15 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0006_expopushtoken_fcm_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expopushtoken',
            name='fcm_token',
        ),
    ]
