# Generated by Django 5.2.5 on 2025-10-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0007_remove_expopushtoken_fcm_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='frequency',
            field=models.CharField(choices=[('1d', 'Daily'), ('3d', '3 Days'), ('7d', 'Weekly'), ('14d', '14 Days'), ('30d', 'Monthly')], default='7d', max_length=30),
        ),
    ]
