# Generated by Django 5.2.5 on 2025-11-12 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0008_alter_reminder_frequency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='insurance',
        ),
    ]
