# Generated by Django 5.2.5 on 2025-09-02 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=30)),
                ('doc_type', models.CharField(max_length=30)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle')),
            ],
            options={
                'verbose_name_plural': 'VehicleDocument',
            },
        ),
    ]
