# Generated by Django 5.2.5 on 2025-11-15 17:01

import cloudinary_storage.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('insurance', 'Insurance'), ('license', 'License'), ('registration', 'Registration'), ('other', 'Other')], default='other', max_length=30)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='images')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle')),
            ],
            options={
                'verbose_name_plural': 'VehicleDocument',
            },
        ),
    ]
