# Generated by Django 5.2.5 on 2025-09-12 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicledocument', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicledocument',
            name='file_path',
        ),
    ]
