# Generated by Django 5.2.5 on 2025-10-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicledocument', '0002_remove_vehicledocument_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledocument',
            name='doc_type',
            field=models.CharField(choices=[('insurance', 'Insurance'), ('license', 'License'), ('registration', 'Registration'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
