# Generated by Django 5.2.5 on 2025-11-10 14:55

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicledocument', '0003_alter_vehicledocument_doc_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledocument',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='images'),
        ),
    ]
