# Generated by Django 5.2.5 on 2025-09-21 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='qr_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
