# Generated by Django 5.2.5 on 2025-09-02 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('familymember', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('plate_number', models.CharField(max_length=20)),
                ('engine_cc', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('family_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familymember.familymember')),
            ],
            options={
                'verbose_name_plural': 'Vehicle',
            },
        ),
    ]
