# Generated by Django 5.2.5 on 2025-11-12 14:18

import cloudinary_storage.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('familymember', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('plate_number', models.CharField(max_length=20)),
                ('engine_cc', models.IntegerField(blank=True, null=True)),
                ('engine_wattage', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_image', models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='vehicle_images/')),
                ('family_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='familymember.familymember')),
            ],
            options={
                'verbose_name_plural': 'Vehicle',
            },
        ),
        migrations.CreateModel(
            name='BluebookRenewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renewal_date', models.DateTimeField()),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bluebook_renewals', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name_plural': 'BluebookRenewal',
            },
        ),
    ]
