# Generated by Django 5.2.5 on 2025-09-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_image',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_images/'),
        ),
    ]
