# Generated by Django 5.2.5 on 2025-09-21 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familymember', '0004_alter_familymember_user'),
        ('vehicles', '0003_vehicle_vehicle_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='family_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='familymember.familymember'),
        ),
    ]
