# Generated by Django 5.2.5 on 2025-11-12 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_vehicle_engine_wattage_alter_vehicle_engine_cc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BluebookRenewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renewal_date', models.DateField()),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bluebook_renewals', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name_plural': 'BluebookRenewal',
            },
        ),
    ]
