# Generated by Django 5.2.5 on 2025-11-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_bluebookrenewal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bluebookrenewal',
            name='renewal_date',
            field=models.DateTimeField(),
        ),
    ]
