name: Keep Render Alive

on:
  schedule:
    # Run every 10 minutes
    - cron: "*/10 * * * *"

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render service
        run: |
          curl -s -o /dev/null -w "%{http_code}" https://django-insurance-tracker.onrender.com/users/api/profile/
